### ISSUE TITLE
Data to test your code

### ISSUE THREAD

**Issue by majaidi** [uzh-rpg/deep_uncertainty_estimation#1]
Hello

Thanks for sharing this. Is there a chance you can share some data to help support the code.

I think it will help massively into putting some of your code into practice.

THanks
AMine

**Comment by mattiasegu** [comment]
Hi @majaidi 

The CIFAR-10 dataset is automatically downloaded at lines 57 and 67, when calling `torchvision.datasets.CIFAR10(...)` with `download=True`.

We will add a comment into the README to make sure that it is clear.
